version: '2.4'
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - postgresdb_connection
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    # volumes:
    #   - "./pgadmin_persistent:/var/lib/pgadmin:rw" 
    ports:
      - "8080:80"
    networks:
      - postgresdb_connection
  ingest_data:
    build: ./ingest_csv_data
    command:
      - --user=root
      - --password=root
      - --host=pgdatabase
      - --port=5432
      - --db=ny_taxi
      - --table_name=yellow_taxi_trips
      - --url=$URL
      - --nrows=10
    networks:
      - postgresdb_connection
networks:
  postgresdb_connection: